from: markdown
output-file: output/example.pdf
template: templates/eisvogel.latex

# note that structured variables may be specified:
variables:
    linkcolor: blue
    urlcolor: blue

metadata-file:
- config/eisvogel.yaml
# or you may use metadata-file: with a single value

table-of-contents: true
toc-depth: 2
number-sections: true
listings: true
reference-links: true

