# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

permissions:
  contents: write
          
jobs:
  Convert:
    runs-on: ubuntu-24.04
    steps:  
    - name: Checkout
      uses: actions/checkout@v6
    - name: Pull pandoc image
      run: docker pull pandoc/extra:3.5.0
    - name: Run Conversion
      run: |
        docker run --rm \
          --platform linux/amd64 \
          --volume "$(pwd):/data" \
          --user "$(id -u):$(id -g)" \
          pandoc/extra:3.5.0 \
          docs/*.md \
          --defaults pandoc.yaml \
          --metadata-file eisvogel.yaml
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        pull: '--rebase --autostash'
