# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
          
jobs:
  Convert:
    runs-on: ubuntu-20.04
    container:
      image: maholick/md-pdf-conversion:testing
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Conversion
      run: pandoc ./docs/*.md --defaults=config/pandoc.yaml 
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.0.0
      - with:
        pull: '--rebase --autostash'

